[build]
  # directory to publish
  publish = "dist/"

  # Default build command.
  command = "gulp build"

  # Functions directory to deploy to AWS
  # functions = "functions/"

  # Node version
  environment = { NODE_VERSION = "14.0.0" }
